# coding: utf-8

"""
Wandelbots NOVA API

Interact with robots in an easy and intuitive way.

The version of the OpenAPI document: 2.6.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class SafetyGeometryBox(BaseModel):
    """
    Box shape defined by a center point and three orthogonal edge midpoints. This representation matches the robot controller's internal format and the `Box` message in the virtual robot.  Unlike a parametric size-and-pose box definition, this format can represent all box orientations produced by the robot controller, including left-handed coordinate systems.
    """  # noqa: E501

    center: Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=3, max_length=3)] = Field(
        description="Center of the box as Vector3 [x, y, z] in [mm]."
    )
    neighbour: Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=9, max_length=9)] = Field(
        description="Three edge midpoint coordinates as a flattened array [x1, y1, z1, x2, y2, z2, x3, y3, z3] in [mm]. Each triplet represents the midpoint of one of the three orthogonal box edges originating from the center. Together, these points define an orthogonal basis that encodes the box’s orientation and size. The distance from the center to each midpoint equals half of the corresponding edge length. This representation supports arbitrary orientations, including left-handed coordinate systems used by robot controllers. "
    )
    __properties: ClassVar[List[str]] = ["center", "neighbour"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SafetyGeometryBox from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SafetyGeometryBox from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({"center": obj.get("center"), "neighbour": obj.get("neighbour")})
        return _obj
