# coding: utf-8

"""
    Wandelbots NOVA API

    Interact with robots in an easy and intuitive way.  > **Note:** API version 2 is experimental and will experience functional changes. 

    The version of the OpenAPI document: 2.0.0 beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModbusIOTypeEnum(str, Enum):
    """
    Value type of the MODBUS input/output variable. Used to interpret the corresponding bits correctly. 
    """

    """
    allowed enum values
    """
    MODBUS_IO_TYPE_UNKNOWN = 'MODBUS_IO_TYPE_UNKNOWN'
    MODBUS_IO_TYPE_BOOL = 'MODBUS_IO_TYPE_BOOL'
    MODBUS_IO_TYPE_UINT16 = 'MODBUS_IO_TYPE_UINT16'
    MODBUS_IO_TYPE_FLOAT32 = 'MODBUS_IO_TYPE_FLOAT32'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModbusIOTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


