# coding: utf-8

"""
Wandelbots NOVA API

Interact with robots in an easy and intuitive way.

The version of the OpenAPI document: 2.6.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class CartesianLimits(BaseModel):
    """
    CartesianLimits
    """  # noqa: E501

    velocity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Cartesian velocity limit in mm/s.")
    acceleration: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Cartesian acceleration limit in mm/s².")
    jerk: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Cartesian jerk limit in mm/s³.  > **NOTE** > > This limit type is experimental and its behavior may change in future releases. ",
    )
    orientation_velocity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Orientation velocity limit in rad/s.")
    orientation_acceleration: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Orientation acceleration limit in rad/s²."
    )
    orientation_jerk: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Orientation jerk limit in rad/s³.  > **NOTE** > > This limit type is experimental and its behavior may change in future releases. ",
    )
    __properties: ClassVar[List[str]] = [
        "velocity",
        "acceleration",
        "jerk",
        "orientation_velocity",
        "orientation_acceleration",
        "orientation_jerk",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CartesianLimits from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CartesianLimits from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "velocity": obj.get("velocity"),
                "acceleration": obj.get("acceleration"),
                "jerk": obj.get("jerk"),
                "orientation_velocity": obj.get("orientation_velocity"),
                "orientation_acceleration": obj.get("orientation_acceleration"),
                "orientation_jerk": obj.get("orientation_jerk"),
            }
        )
        return _obj
