# coding: utf-8

"""
Wandelbots NOVA API

Interact with robots in an easy and intuitive way.

The version of the OpenAPI document: 2.6.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from wandelbots_api_client.v2.models.collision_free_algorithm import CollisionFreeAlgorithm
from wandelbots_api_client.v2.models.collision_setup_value_or_key import CollisionSetupValueOrKey
from wandelbots_api_client.v2.models.direction_constraint import DirectionConstraint
from wandelbots_api_client.v2.models.motion_group_setup import MotionGroupSetup
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class PlanCollisionFreeRequest(BaseModel):
    """
    PlanCollisionFreeRequest
    """  # noqa: E501

    motion_group_setup: MotionGroupSetup = Field(
        description="The data to assemble the robot setup can be retrieved from the [getMotionGroupDescription](#/operations/getMotionGroupDescription) endpoint."
    )
    collision_setups: Optional[Dict[str, CollisionSetupValueOrKey]] = Field(
        default=None,
        description="Optional collision setups with support for store keys. If set, overrides motion_group_setup.collision_setups. Each value is either an inline CollisionSetup object or a storage key reference. Storage keys are resolved against the {cell} path parameter of the request URL, which determines the storage bucket. ",
    )
    start_joint_position: List[Union[StrictFloat, StrictInt]] = Field(
        description="Starting joint position for the collision-free motion. Must contain exactly the same number of values as joints in the motion group. To retrieve the current joint position, use the endpoint [getCurrentMotionGroupState](#/operations/getCurrentMotionGroupState). "
    )
    target: List[Union[StrictFloat, StrictInt]] = Field(
        description="The target joint position of the motion. Must contain exactly the same number of values as joints in the motion group. To compute target joint position from a TCP pose, use the endpoint [inverseKinematics](#/operations/inverseKinematics). "
    )
    constraint: Optional[DirectionConstraint] = Field(
        default=None,
        description="Optional constraint for the motion. If provided, the motion will be constrained accordingly.  > **NOTE** > > Constraints are experimental and their behavior may change in future releases. ",
    )
    algorithm: CollisionFreeAlgorithm
    __properties: ClassVar[List[str]] = [
        "motion_group_setup",
        "collision_setups",
        "start_joint_position",
        "target",
        "constraint",
        "algorithm",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlanCollisionFreeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of motion_group_setup
        if self.motion_group_setup:
            _dict["motion_group_setup"] = self.motion_group_setup.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in collision_setups (dict)
        _field_dict = {}
        if self.collision_setups:
            for _key_collision_setups in self.collision_setups:
                if self.collision_setups[_key_collision_setups]:
                    _field_dict[_key_collision_setups] = self.collision_setups[_key_collision_setups].to_dict()
            _dict["collision_setups"] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of constraint
        if self.constraint:
            _dict["constraint"] = self.constraint.to_dict()
        # override the default output from pydantic by calling `to_dict()` of algorithm
        if self.algorithm:
            _dict["algorithm"] = self.algorithm.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlanCollisionFreeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "motion_group_setup": MotionGroupSetup.from_dict(obj["motion_group_setup"])
                if obj.get("motion_group_setup") is not None
                else None,
                "collision_setups": dict((_k, CollisionSetupValueOrKey.from_dict(_v)) for _k, _v in obj["collision_setups"].items())
                if obj.get("collision_setups") is not None
                else None,
                "start_joint_position": obj.get("start_joint_position"),
                "target": obj.get("target"),
                "constraint": DirectionConstraint.from_dict(obj["constraint"]) if obj.get("constraint") is not None else None,
                "algorithm": CollisionFreeAlgorithm.from_dict(obj["algorithm"]) if obj.get("algorithm") is not None else None,
            }
        )
        return _obj
