[core]
reloadable = true
order = 1000      # Make sure all .dlls are loaded before this extension

[package]
target.python = ["cp312"]
target.platform = ["linux-x86_64"]
version = "2.26.0"
category = "Simulation"
title = "Wandelbots NOVA"
description = "Simulate your robotics cell running on Wandelbots NOVA."
authors = ["Wandelbots GmbH"]
repository = ""
keywords = [
    "Wandelbots",
    "WandelbotsNOVA",
    "NOVA",
    "Robotics",
    "Simulation",
    "Articulation",
    "Manufacturing",
    "UR",
    "Fanuc",
    "Yaskawa",
    "Kuka",
    "ABB",
    "UniversalRobots",
]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"wandelbots.usd" = { version = "1.1.5" }
"isaacsim.core.api" = {}
"isaacsim.core.prims" = {}
"isaacsim.core.utils" = {}
"isaacsim.gui.components" = {}
'omni.services.core' = {}
"isaacsim.core.cloner" = {}
'omni.services.client' = {}
'omni.services.usd' = {}
"omni.services.transport.server.base" = {}
"omni.services.transport.server.http" = {}
"omni.services.transport.client.http_async" = {}
"omni.kit.test" = {}
"omni.graph" = {}
"omni.kit.clipboard" = {}
"omni.ui" = {}
"omni.kit.menu.utils" = {}
"omni.replicator.core" = {}
"isaacsim.sensors.camera" = {}
"omni.isaac.ml_archive" = {}
"omni.kit.property.usd" = {}
"omni.kit.browser.folder.core" = {}
"omni.kit.browser.core" = {}
"omni.kit.commands" = {}
"omni.usd" = {}
"omni.kit.notification_manager" = {}
"omni.kit.actions.core" = {}

[settings]
exts."omni.services.transport.server.http".https.enabled = false
exts."omni.services.transport.server.http".ssl.ssl_cert_reqs = 1     #CERT_OPTIONAL
exts."omni.services.transport.server.http".ssl.ssl_ciphers = "TLSv1"
exts."omni.services.transport.server.http".ssl.ssl_keyfile = ""
exts."omni.services.transport.server.http".ssl.ssl_certfile = ""


# Uncomment this line to define the port for the APIs
# - HTTP has default port 8211 but can be 8011 when 8211 is not available
# - HTTPS is always accessible through 8433
# exts."omni.services.transport.server.http".port=8211

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[[python.module]]
name = "wandelbots.omni"

[[python.module]]
name = "wandelbots"

[[python.module]]
path = "pip_prebundle"

[[test]]
name = "startup"
pythonTests.include = []
_startup_only_test = true
timeout = 3600


[[test]]
name = "unit"
pythonTests.include = ["wandelbots.omni.tests.unit.*"]
