# coding: utf-8

"""
Wandelbots NOVA API

Interact with robots in an easy and intuitive way.

The version of the OpenAPI document: 2.6.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List
from wandelbots_api_client.v2.models.cloud_status_checks import CloudStatusChecks
from wandelbots_api_client.v2.models.cloud_status_errors import CloudStatusErrors
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class CloudStatus(BaseModel):
    """
    CloudStatus
    """  # noqa: E501

    ready: StrictBool = Field(
        description="Whether NOVA Cloud is fully reachable, i.e. every reachability check passed. `false` when the instance is not configured or any check fails."
    )
    checks: CloudStatusChecks
    errors: CloudStatusErrors
    checked_at: datetime = Field(description="Timestamp at which the reachability checks were performed (RFC 3339).")
    __properties: ClassVar[List[str]] = ["ready", "checks", "errors", "checked_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CloudStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of checks
        if self.checks:
            _dict["checks"] = self.checks.to_dict()
        # override the default output from pydantic by calling `to_dict()` of errors
        if self.errors:
            _dict["errors"] = self.errors.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CloudStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "ready": obj.get("ready"),
                "checks": CloudStatusChecks.from_dict(obj["checks"]) if obj.get("checks") is not None else None,
                "errors": CloudStatusErrors.from_dict(obj["errors"]) if obj.get("errors") is not None else None,
                "checked_at": obj.get("checked_at"),
            }
        )
        return _obj
